# Generated by Django 5.2.5 on 2025-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_credits',
            field=models.PositiveIntegerField(default=1, verbose_name='Test Hakkı'),
        ),
        migrations.AddField(
            model_name='user',
            name='tests_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamamlanan Test Sayısı'),
        ),
    ]
