# Generated by Django 5.2.5 on 2025-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('initial', 'İlk Değerlendirme'), ('progress', 'İlerleme Raporu')], default='initial', max_length=20)),
                ('test_number', models.IntegerField(default=1)),
                ('markdown_content', models.TextField()),
                ('html_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Raporu',
                'verbose_name_plural': 'AI Raporları',
                'db_table': 'ai_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeminiService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('model_name', models.CharField(default='gemini-1.5-pro', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gemini AI Servisi',
                'verbose_name_plural': 'Gemini AI Servisleri',
                'db_table': 'gemini_service',
            },
        ),
    ]
