"""
Django settings for selfmode_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv # .env dosyasını okumak için
import dj_database_url # Render veritabanı için

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env dosyasını yükle
dotenv.load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True' # Varsayılan olarak False yapıldı

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    'selfmode.app',
    '.onrender.com' # Render'ın kendi domainlerini de ekliyoruz
]

# Render için CSRF ayarı
CSRF_TRUSTED_ORIGINS = [
    'https://selfmode.app',
    'https://*.onrender.com'
]

# Application definition

# Custom User Model
AUTH_USER_MODEL = 'user_management.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'user_management',
    'assessments',
    'ai_services',
    'main',
    'payments', # Ödeme sistemi için yeni uygulama
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'selfmode_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'selfmode_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Render.com PostgreSQL veritabanı ayarı
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        ssl_require=True
    )

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # Development only
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
]
CORS_ALLOWED_HEADERS = ['*']
CORS_ALLOWED_METHODS = ['*']

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Gemini AI Settings
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Shopier API Ayarları
SHOPIER_PAT = os.getenv('SHOPIER_PAT', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIwYmYyNmFiNDNlOGExMGE1OTBiYTEzYWUwODAyZjcyMCIsImp0aSI6IjNmMmJhOTBkYzQ3MzM3MzdiMTk2MGFhNWY5MWVhOGU4NmUzOTRmMTc0ZjQyOGJjZTc2MTRmMjQ2YTY1YzZhODZiMTViMGY4NzIxMzcwZDU5ZTM4ZGFmZWM1YmEwYjFjZGIxMDRiNmU4MjI3M2NlMTE5NzBmNGQyMjJjZTg2NWM5YjBiZjEyN2YwM2UxMDljOTQxMTMyM2RkMjdiYmFiODUiLCJpYXQiOjE3NTY2NDYyNjQsIm5iZiI6MTc1NjY0NjI2NCwiZXhwIjoxOTE0NDMxMDI0LCJzdWIiOiIyNjM2NTcxIiwic2NvcGVzIjpbIm9yZGVyczpyZWFkIiwib3JkZXJzOndyaXRlIiwicHJvZHVjdHM6cmVhZCIsInByb2R1Y3RzOndyaXRlIiwic2hpcHBpbmdzOnJlYWQiLCJzaGlwcGluZ3M6d3JpdGUiLCJkaXNjb3VudHM6cmVhZCIsImRpc2NvdW50czp3cml0ZSIsInBheW91dHM6cmVhZCIsInJlZnVuZHM6cmVhZCIsInJlZnVuZHM6d3JpdGUiLCJzaG9wOnJlYWQiLCJzaG9wOndyaXRlIl19.U_s3LiQ3OpV9AaWsNnqwIMiCt4-uz3re6JzUnCNU09UI58f1ojRVfqe2atJZSNxcCe6fbP5b7ZWE8i3POt9gozVLbakxDIz0tisUZuRNpie-wD-W6Ecjr0DNc3p4BrY7ZG-FK7wGXyCKE-uwQVwOONgEUilBzJyoJNshWj1oLsA8nzjYedViHLGHplPhoEqn2V5Nb4y2LZ0950-8u1K6tjRut7hLv3-4HQuvQjvxJdbQuXwznFiRuAlnj_xPHMk5plfbSosihqHI1wLDXUU2Iv7Aa0gBgS1cyH7LEYsSStThY4l_eZJaFCrEZR0f0DAoJZyY7JEKLxY4vPsXW5B-QQ')

# Authentication Settings
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
