# Generated by Django 5.2.5 on 2025-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeWheelAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(default=1)),
                ('career', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=0)),
                ('relationships', models.IntegerField(default=0)),
                ('personal_growth', models.IntegerField(default=0)),
                ('finances', models.IntegerField(default=0)),
                ('home', models.IntegerField(default=0)),
                ('fun', models.IntegerField(default=0)),
                ('spirituality', models.IntegerField(default=0)),
                ('goal1', models.CharField(blank=True, max_length=200)),
                ('goal2', models.CharField(blank=True, max_length=200)),
                ('goal3', models.CharField(blank=True, max_length=200)),
                ('target_career', models.IntegerField(default=0)),
                ('target_health', models.IntegerField(default=0)),
                ('target_relationships', models.IntegerField(default=0)),
                ('target_personal_growth', models.IntegerField(default=0)),
                ('target_finances', models.IntegerField(default=0)),
                ('target_home', models.IntegerField(default=0)),
                ('target_fun', models.IntegerField(default=0)),
                ('target_spirituality', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yaşam Çarkı Değerlendirmesi',
                'verbose_name_plural': 'Yaşam Çarkı Değerlendirmeleri',
                'db_table': 'life_wheel_assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
