# Generated by Django 5.2.5 on 2025-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifewheelassessment',
            name='employment_status',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('employed', 'Çalışan'), ('unemployed', 'İşsiz'), ('retired', 'Emekli'), ('entrepreneur', 'Girişimci')], default='employed', max_length=20, verbose_name='Çalışma Durumu'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ünvan (Çalıştığı yerdeki görevi)'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Bekar'), ('married', 'Evli'), ('divorced', 'Boşanmış'), ('widowed', 'Dul'), ('relationship', 'İlişkisi var')], default='single', max_length=20, verbose_name='Medeni Durum'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meslek (Eğitimini Aldığı)'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal1',
            field=models.CharField(blank=True, max_length=200, verbose_name='1. Hedef'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal2',
            field=models.CharField(blank=True, max_length=200, verbose_name='2. Hedef'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal3',
            field=models.CharField(blank=True, max_length=200, verbose_name='3. Hedef'),
        ),
    ]
