# Generated by Django 5.2.5 on 2025-08-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_lifewheelassessment_employment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifewheelassessment',
            name='home',
        ),
        migrations.RemoveField(
            model_name='lifewheelassessment',
            name='target_home',
        ),
        migrations.RemoveField(
            model_name='lifewheelassessment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='family',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='social_life',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='sports',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='target_family',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='target_social_life',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='target_sports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='career',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='employment_status',
            field=models.CharField(default='employed', max_length=50),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='finances',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='fun',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal1',
            field=models.CharField(blank=True, max_length=255, verbose_name='1. Hedef'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal2',
            field=models.CharField(blank=True, max_length=255, verbose_name='2. Hedef'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='goal3',
            field=models.CharField(blank=True, max_length=255, verbose_name='3. Hedef'),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='health',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='marital_status',
            field=models.CharField(default='single', max_length=50),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='personal_growth',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='relationships',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='spirituality',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_career',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_finances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_fun',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_health',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_personal_growth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_relationships',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='target_spirituality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifewheelassessment',
            name='test_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
