# Generated by Django 5.2.5 on 2025-08-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_lifewheelassessment_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifewheelassessment',
            name='age_range',
            field=models.CharField(default='25-34', max_length=20, verbose_name='Yaş Aralığı'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='education_level',
            field=models.CharField(default='bachelor', max_length=20, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Çocuk Durumu'),
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='living_area',
            field=models.CharField(default='city', max_length=20, verbose_name='Yaşam Alanı'),
        ),
    ]
