# Generated by Django 5.2.5 on 2025-08-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_lifewheelassessment_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifewheelassessment',
            name='priorities',
            field=models.TextField(blank=True, verbose_name='Öncelikler'),
        ),
    ]
