# Generated by Django 5.2.5 on 2025-08-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_lifewheelassessment_priorities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifewheelassessment',
            name='has_children',
        ),
        migrations.AddField(
            model_name='lifewheelassessment',
            name='children_status',
            field=models.CharField(default='none', max_length=10, verbose_name='Çocuk Durumu'),
        ),
    ]
